version: 0.2

phases:
  install:
    commands:
      - npm install -g serverless
  pre_build:
    commands:
      - curl -fL https://github.com/coursier/coursier/releases/latest/download/cs-x86_64-pc-linux.gz | gzip -d > cs && chmod +x cs && ./cs setup
  build:
    commands:
      - sls deploy -v
